#!/usr/bin/python3

# non tail recursion
def factorial(n: int) -> int:
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

print(factorial(5))

def fibonacci(n: int) -> int:
    if n == 0:
        return 0
    elif n == 1: 
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(12))

def tail_fact(n, acc = 1):
    if n == 0:
        return acc
    else:
        return tail_fact(n - 1, acc * n)

print(tail_fact(7))

